name: Deploy to Lightsail

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS CLI and Lightsailctl
      - name: Install AWS CLI and Lightsailctl
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
          sudo curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
          sudo chmod +x /usr/local/bin/lightsailctl
          aws --version
          lightsailctl --version

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      # Build and push Docker image to Lightsail
      - name: Build and Push to Lightsail
        id: push_image
        run: |
          docker build -t frc-fantasy:latest .
          PUSH_OUTPUT=$(aws lightsail push-container-image --service-name frc-fantasy-service --label frc-fantasy --image frc-fantasy:latest)
          echo "$PUSH_OUTPUT"
          IMAGE_REF=$(echo "$PUSH_OUTPUT" | grep -o ":frc-fantasy-service.frc-fantasy.[0-9]*" | head -n 1)
          if [ -z "$IMAGE_REF" ]; then
            echo "Error: Could not extract IMAGE_REF from push output"
            exit 1
          fi
          echo "image_ref=$IMAGE_REF" >> $GITHUB_OUTPUT

      # Deploy the new image
      - name: Deploy to Lightsail
        run: |
          cat <<EOF > deployment.json
          {
            "containers": {
              "frc-fantasy": {
                "image": "${{ steps.push_image.outputs.image_ref }}",
                "ports": {
                  "5000": "HTTP"
                },
                "environment": {
                  "DB_USER": "${{ secrets.DB_USER }}",
                  "DB_PASSWORD": "${{ secrets.DB_PASSWORD }}",
                  "DB_HOST": "${{ secrets.DB_HOST }}",
                  "DB_PORT": "${{ secrets.DB_PORT }}",
                  "DB_NAME": "${{ secrets.DB_NAME }}"
                }
              }
            },
            "publicEndpoint": {
              "containerName": "frc-fantasy",
              "containerPort": 5000
            }
          }
          EOF
          aws lightsail create-container-service-deployment --service-name frc-fantasy-service --cli-input-json file://deployment.json